<#
  yiclaude — Windows installer: Claude Code + a domestic Chinese model.
  Native PowerShell entry point (use this on Windows; install.sh is for macOS/Linux).

  Beginner mode (no arguments) = a guided wizard:
    1. pick a model from a menu
    2. if you have an API key, paste it; if not, it opens the page and waits
    3. it installs Git + Claude Code and configures everything for you

  One command (run in PowerShell):
    irm https://cdn.jsdelivr.net/gh/your-name/yiclaude@main/install.ps1 | iex

  With flags:
    & ([scriptblock]::Create((irm https://cdn.jsdelivr.net/gh/your-name/yiclaude@main/install.ps1))) -Model glm -ApiKey sk-xxx

  Notes:
    - Targets Windows 10 (1809+) and Windows 11. Installs whatever is missing.
    - Claude Code on Windows runs commands through Git Bash, so Git is required.
    - Tries the official source first, then a China mirror as fallback.
#>
[CmdletBinding()]
param(
  [string]$Model = "glm",
  [string]$ApiKey = "",
  [string]$ModelId = "",
  [string]$FastModel = "",
  [string]$BaseUrl = "",
  [ValidateSet("zh","en")][string]$Lang = "zh",
  [switch]$NoVerify,
  [switch]$NoOpen,
  [switch]$List,
  [switch]$Help
)

$ErrorActionPreference = "Stop"

# Force UTF-8 so Chinese text and box-drawing render on every console
# (legacy conhost, Windows Terminal, VS Code, PowerShell 5.1 and 7).
try {
  $OutputEncoding = [System.Text.UTF8Encoding]::new()
  [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
  chcp 65001 > $null 2>&1
} catch {}

$Version = "1.0.0"
$RepoUrl = "https://github.com/your-name/yiclaude"
$ModelSet = $PSBoundParameters.ContainsKey('Model')
$KeySet   = $PSBoundParameters.ContainsKey('ApiKey')
$TotalSteps = if ($NoVerify) { 3 } else { 4 }
$script:Step = 0
$script:Failed = $false

# ---- bilingual helper ------------------------------------------------------
function T($zh, $en) { if ($Lang -eq "en") { $en } else { $zh } }

# ---- provider registry (China-first endpoints) ----------------------------
$Providers = [ordered]@{
  glm      = @{ label="智谱 GLM";        base="https://open.bigmodel.cn/api/anthropic"; model="glm-4.6";              fast="glm-4.5-air";          key="https://open.bigmodel.cn/usercenter/apikeys";                            doc="https://docs.bigmodel.cn/cn/guide/start/quick-start" }
  kimi     = @{ label="Kimi (Moonshot)"; base="https://api.moonshot.cn/anthropic";       model="kimi-k2-0905-preview"; fast="kimi-k2-0905-preview"; key="https://platform.moonshot.cn/console/api-keys";                          doc="https://platform.moonshot.cn/blog/posts/kimi-api-quick-start-guide" }
  minimax  = @{ label="MiniMax";         base="https://api.minimaxi.com/anthropic";      model="MiniMax-M2.1";         fast="MiniMax-M2.1";         key="https://platform.minimaxi.com/user-center/basic-information/interface-key"; doc="https://platform.minimaxi.com/docs/token-plan/claude-code" }
  qwen     = @{ label="通义千问 Qwen";   base="https://dashscope.aliyuncs.com/apps/anthropic"; model="qwen3-coder-plus"; fast="qwen3-coder-plus";  key="https://bailian.console.aliyun.com/?tab=model#/api-key";                  doc="https://help.aliyun.com/zh/model-studio/claude-code" }
  deepseek = @{ label="DeepSeek";        base="https://api.deepseek.com/anthropic";      model="deepseek-v4-pro[1m]";  fast="deepseek-v4-flash";    key="https://platform.deepseek.com/api_keys";                                  doc="https://api-docs.deepseek.com/zh-cn/quick_start/" }
}

function Test-ApiKeyLooksPlausible([string]$Candidate) {
  if ([string]::IsNullOrWhiteSpace($Candidate)) { return $false }
  if ($Candidate.Length -lt 16) { return $false }
  if ($Candidate -match '\s|<|>|API key|api key|your |你的|创建|新建|复制|粘贴|generated') { return $false }
  return $true
}

function Assert-ApiKeyLooksPlausible {
  if (Test-ApiKeyLooksPlausible $ApiKey) { return }
  Die (T "这不像有效 API key。请粘贴厂商控制台生成的完整 key，不要粘贴说明文字或占位符。" "this does not look like a valid API key. Paste the full key generated by the provider console, not instructions or placeholders.")
}

# ---- UI primitives ---------------------------------------------------------
function Banner {
  Write-Host ""
  Write-Host "  ╭────────────────────────────────────────────────────╮" -ForegroundColor Cyan
  Write-Host "  │     yiclaude · Claude Code 一键安装器                │" -ForegroundColor Cyan
  Write-Host "  │     install Claude Code + a China LLM, one command   │" -ForegroundColor Cyan
  Write-Host "  ╰────────────────────────────────────────────────────╯" -ForegroundColor Cyan
  Write-Host "  v$Version · $RepoUrl" -ForegroundColor DarkGray
}
function Note($m) { Write-Host "  $m" -ForegroundColor DarkGray }
function Ok($m)   { Write-Host "  ✓ $m" -ForegroundColor Green }
function Warn($m) { Write-Host "  ! $m" -ForegroundColor Yellow }
function Die($m)  {
  Write-Host ""
  Write-Host "  ✗ $(T '出错了' 'Error'): $m" -ForegroundColor Red
  exit 1
}
function Begin-Step($title) {
  $script:Step++
  Write-Host ""
  Write-Host "▸ [$($script:Step)/$TotalSteps] $title" -ForegroundColor Cyan
  Write-Progress -Activity "yiclaude" -Status $title -PercentComplete ([int]($script:Step * 100 / $TotalSteps))
}
function Have-Cmd($name) { $null -ne (Get-Command $name -ErrorAction SilentlyContinue) }
function Refresh-Path {
  $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" +
              [System.Environment]::GetEnvironmentVariable("Path","User")
}

function Show-Help {
  Banner
  Write-Host ""
  Write-Host (T "用法:" "Usage:")
  Write-Host "  irm $RepoUrl/raw/main/install.ps1 | iex        $(T '# 交互向导' '# interactive wizard')"
  Write-Host "  ... -Model glm -ApiKey <key>                   $(T '# 已有 key' '# if you already have a key')"
  Write-Host ""
  Write-Host (T "选项:" "Options:")
  Write-Host "  -Model <name>     glm | kimi | minimax | qwen | deepseek  $(T '(默认 glm)' '(default glm)')"
  Write-Host "  -ApiKey <key>     $(T '你的 API key（不填则交互输入）' 'your API key (asked interactively if omitted)')"
  Write-Host "  -ModelId <id>     $(T '覆盖默认模型名' 'override the model id')"
  Write-Host "  -BaseUrl <url>    $(T '覆盖接口地址' 'override the base URL')"
  Write-Host "  -Lang <zh|en>     $(T '界面语言 (默认 zh)' 'UI language (default zh)')"
  Write-Host "  -NoVerify         $(T '跳过连通性验证' 'skip the connectivity check')"
  Write-Host "  -NoOpen           $(T '缺 key 时不自动打开浏览器' 'do not auto-open the key page')"
  Write-Host "  -List             $(T '列出支持的厂商' 'list supported providers')"
  Write-Host "  -Help             $(T '显示帮助' 'show this help')"
}

function Show-List {
  Banner
  Write-Host ""
  Write-Host (T "支持的模型厂商：" "Supported providers:")
  foreach ($k in $Providers.Keys) {
    $p = $Providers[$k]
    Write-Host ("  {0,-9} {1,-16} {2}" -f $k, $p.label, $p.base)
  }
}

# ---- interactive wizard ----------------------------------------------------
function Select-Provider {
  Write-Host ""
  Write-Host "  $(T '第一步：选择要用的模型（输入数字后回车）' 'Step 1: choose a model (type a number, Enter)')" -ForegroundColor White
  Write-Host "    1) 智谱 GLM        $(T '推荐 · 编程最强' 'recommended · best at coding')" -ForegroundColor Cyan
  Write-Host "    2) Kimi (Moonshot) $(T '长上下文' 'long context')" -ForegroundColor Cyan
  Write-Host "    3) MiniMax         $(T '便宜' 'cheap')" -ForegroundColor Cyan
  Write-Host "    4) 通义千问 Qwen   $(T '阿里' 'Alibaba')" -ForegroundColor Cyan
  Write-Host "    5) DeepSeek        $(T '推理强' 'strong reasoning')" -ForegroundColor Cyan
  $c = Read-Host (T "  你的选择 [1]" "  Your choice [1]")
  switch ($c) {
    "2" { $script:Model = "kimi" }
    "3" { $script:Model = "minimax" }
    "4" { $script:Model = "qwen" }
    "5" { $script:Model = "deepseek" }
    default { $script:Model = "glm" }
  }
  Ok "$(T '已选择：' 'Selected: ')$($Providers[$Model].label)"
}

function Acquire-Key {
  $p = $Providers[$Model]
  $ans = Read-Host (T "  第二步：你有 $($p.label) 的 API key 吗？(y/N)" "  Step 2: do you have a $($p.label) API key? (y/N)")
  if ($ans -notmatch '^(y|yes)$') {
    if (-not $NoOpen) { try { Start-Process $p.key } catch {} }
    Write-Host ""
    Write-Host "  $(T '没关系，照下面 4 步走，1 分钟就能拿到：' 'No problem — 4 steps, about 1 minute:')" -ForegroundColor Yellow
    Write-Host "    1  $(T "打开 $($p.label) 的 API key 页面（已自动帮你打开浏览器；没弹出就手动复制下面链接）" "Open the $($p.label) API key page (auto-opened; if not, copy the link)")" -ForegroundColor Green
    Write-Host "       $($p.key)" -ForegroundColor Cyan
    Write-Host "    2  $(T '注册或登录账号（部分厂商需要先实名认证）' 'Register or sign in (some need ID verification first)')" -ForegroundColor Green
    Write-Host "    3  $(T '点“创建 / 新建 API Key”，复制那串 key' "Click 'Create API Key' and copy the key")" -ForegroundColor Green
    Write-Host "    4  $(T '回到这个窗口，粘贴进来按回车' 'Come back here, paste it, press Enter')" -ForegroundColor Green
    Write-Host "    $(T '看不懂可参考官方图文文档：' 'Official docs:') $($p.doc)" -ForegroundColor DarkGray
  }
  while ($true) {
    $script:ApiKey = Read-Host (T "  把 API key 粘贴到这里，然后回车" "  Paste your API key here, then Enter")
    if ([string]::IsNullOrWhiteSpace($script:ApiKey)) {
      Warn (T "还没收到 key，再粘贴一次（或按 Ctrl+C 退出）" "no key yet — paste again (or Ctrl+C to quit)")
      continue
    }
    if (Test-ApiKeyLooksPlausible $script:ApiKey) { break }
    Warn (T "这看起来不像 API key。请只粘贴厂商控制台生成的那串 key。" "that does not look like an API key. Paste only the key generated by the provider console.")
    $script:ApiKey = ""
  }
  Ok (T "已收到 API key" "API key received")
}

# ---- prerequisites: install whatever is missing ---------------------------
function Install-GitFromMirror {
  # Fallback when winget is unavailable or failed: download the official
  # Git for Windows installer from a China mirror and run it silently.
  Note (T "改用国内镜像下载 Git 安装包…" "Falling back to a China mirror for Git…")
  $base = "https://mirrors.huaweicloud.com/git-for-windows"
  $idx  = Invoke-WebRequest -Uri "$base/" -UseBasicParsing -TimeoutSec 30
  $ver  = ($idx.Links.href | Where-Object { $_ -match '^v?\d+\.\d+' } |
           Sort-Object -Descending | Select-Object -First 1).TrimEnd('/')
  $page = Invoke-WebRequest -Uri "$base/$ver/" -UseBasicParsing -TimeoutSec 30
  $file = ($page.Links.href | Where-Object { $_ -match 'Git-.*-64-bit\.exe$' } | Select-Object -First 1)
  if (-not $file) { throw "no installer found on mirror" }
  $out  = Join-Path $env:TEMP $file
  Invoke-WebRequest -Uri "$base/$ver/$file" -OutFile $out -UseBasicParsing -TimeoutSec 600
  Start-Process -FilePath $out -ArgumentList "/VERYSILENT","/NORESTART","/NOCANCEL" -Wait
}

function Ensure-Git {
  if (Have-Cmd "git") { Ok (T "Git 已安装" "Git already installed"); return }
  Warn (T "未发现 Git，正在安装（Claude Code 在 Windows 上靠它跑命令）" "Git not found; installing (Claude Code needs it on Windows)")
  if (Have-Cmd "winget") {
    try { winget install --id Git.Git -e --accept-source-agreements --accept-package-agreements | Out-Null } catch {}
    Refresh-Path
    if (Have-Cmd "git") { Ok (T "Git 安装完成（官方/winget）" "Git installed (winget)"); return }
  }
  try { Install-GitFromMirror; Refresh-Path } catch {}
  if (Have-Cmd "git") { Ok (T "Git 安装完成（国内镜像）" "Git installed (mirror)"); return }
  Die (T "Git 自动安装失败。请手动装 Git for Windows 后重试：https://git-scm.com/download/win" "Auto-install of Git failed. Install Git for Windows manually, then retry: https://git-scm.com/download/win")
}

function Step-Prereq {
  Begin-Step (T "检查并安装前置依赖" "Check & install prerequisites")
  Ok (T "系统: Windows" "OS: Windows")
  if (-not (Have-Cmd "winget")) {
    Warn (T "未发现 winget（应用安装程序）；会尽量用国内镜像直接装。建议从 Microsoft Store 更新“应用安装程序”以获得最佳体验。" "winget (App Installer) not found; will use China mirrors directly. Updating 'App Installer' from Microsoft Store is recommended.")
  }
  Ensure-Git
}

# ---- install Claude Code (official first, then winget) ---------------------
function Step-InstallClaude {
  Begin-Step (T "安装 Claude Code" "Install Claude Code")
  if (Have-Cmd "claude") { Ok (T "Claude Code 已安装" "Claude Code already installed"); return }
  Note (T "先试官方源，失败再用 winget" "Trying official source first, then winget")
  $done = $false
  try {
    Invoke-RestMethod -Uri "https://claude.ai/install.ps1" -TimeoutSec 20 | Invoke-Expression
    Refresh-Path
    if (Have-Cmd "claude") { $done = $true }
  } catch {}
  if (-not $done -and (Have-Cmd "winget")) {
    try { winget install --id Anthropic.ClaudeCode -e --accept-source-agreements --accept-package-agreements | Out-Null } catch {}
    Refresh-Path
    if (Have-Cmd "claude") { $done = $true }
  }
  if (-not $done) {
    Die (T "Claude Code 安装失败，请看上面的输出，或关掉 PowerShell 重开再试" "Claude Code install failed; check output or reopen PowerShell")
  }
  Ok (T "Claude Code 安装完成" "Claude Code installed")
}

# ---- configure model: safe-merge into settings.json -----------------------
# We merge our env keys into any existing ~/.claude/settings.json (preserving
# the user's other fields) using PowerShell's native JSON — no python/jq needed.
# The result is a clean settings.json that cc-switch can later import.
function Step-Configure {
  $p = $Providers[$Model]
  Begin-Step (T "配置模型：$($p.label)" "Configure model: $($p.label)")
  if (-not $BaseUrl)   { $script:BaseUrl   = $p.base }
  if (-not $ModelId)   { $script:ModelId   = $p.model }
  if (-not $FastModel) { $script:FastModel = $p.fast }

  $dir = Join-Path $env:USERPROFILE ".claude"
  New-Item -ItemType Directory -Force -Path $dir | Out-Null
  $path = Join-Path $dir "settings.json"

  $data = $null
  if (Test-Path $path) {
    Copy-Item $path "$path.bak" -Force
    try { $data = Get-Content $path -Raw | ConvertFrom-Json } catch { $data = $null }
  }
  if ($null -eq $data) { $data = [pscustomobject]@{} }

  $envObj = $null
  if ($data.PSObject.Properties.Name -contains 'env') { $envObj = $data.env }
  if ($null -eq $envObj) { $envObj = [pscustomobject]@{} }

  $envObj | Add-Member -NotePropertyName 'ANTHROPIC_BASE_URL'         -NotePropertyValue $BaseUrl   -Force
  $envObj | Add-Member -NotePropertyName 'ANTHROPIC_AUTH_TOKEN'       -NotePropertyValue $ApiKey    -Force
  $envObj | Add-Member -NotePropertyName 'ANTHROPIC_MODEL'            -NotePropertyValue $ModelId   -Force
  $envObj | Add-Member -NotePropertyName 'ANTHROPIC_SMALL_FAST_MODEL' -NotePropertyValue $FastModel -Force
  $data | Add-Member -NotePropertyName 'env' -NotePropertyValue $envObj -Force

  # Write UTF-8 WITHOUT BOM (Claude Code's JSON parser rejects a leading BOM).
  $json = $data | ConvertTo-Json -Depth 12
  [System.IO.File]::WriteAllText($path, $json, (New-Object System.Text.UTF8Encoding($false)))

  Ok "$(T '已写入配置：' 'Config written: ')$path"
  Note "base_url = $BaseUrl"
  Note "model    = $ModelId"
}

# ---- verify connectivity ---------------------------------------------------
function Step-Verify {
  if ($NoVerify) { return }
  Begin-Step (T "验证连通性" "Verify connectivity")
  $p = $Providers[$Model]
  $headers = @{ "content-type"="application/json"; "anthropic-version"="2023-06-01"; "authorization"="Bearer $ApiKey" }
  $payload = @{ model=$ModelId; max_tokens=8; messages=@(@{ role="user"; content="ping" }) } | ConvertTo-Json -Depth 6
  $code = 0
  try {
    $resp = Invoke-WebRequest -Uri "$($BaseUrl.TrimEnd('/'))/v1/messages" -Method Post -Headers $headers -Body $payload -TimeoutSec 40 -UseBasicParsing
    $code = [int]$resp.StatusCode
  } catch {
    if ($_.Exception.Response) { $code = [int]$_.Exception.Response.StatusCode.value__ }
  }
  if ($code -eq 200) { Ok (T "连接成功，模型可用！" "Connected — the model works!"); return }
  Warn (T "验证失败 (HTTP $code)。常见原因：" "Verify failed (HTTP $code). Common causes:")
  switch ($code) {
    { $_ -in 401,403 } { Write-Host "  $(T '→ API key 不对或没权限' '→ wrong/unauthorized API key')" }
    404                { Write-Host "  $(T '→ 接口地址不对，或该厂商路径有变' '→ wrong base URL or path changed')" }
    { $_ -in 400,422 } { Write-Host "  $(T '→ 模型名可能过期，试试 -ModelId <新模型名>' '→ model id may be stale — try -ModelId <id>')" }
    default            { Write-Host "  $(T '→ 网络不通或超时' '→ network error or timeout')" }
  }
  Write-Host "  $(T '厂商文档：' 'Provider docs: ')$($p.doc)"
  Warn (T "配置已写入，但模型暂不可用。修正后重跑即可。" "Config written but model not usable yet. Fix and re-run.")
  $script:Failed = $true
}

function Summary {
  $p = $Providers[$Model]
  Write-Host ""
  Write-Host "------------------------------------------------------------" -ForegroundColor DarkGray
  if ($script:Failed) {
    Write-Host "  ⚠ $(T '安装完成，但验证未通过（见上）' 'Installed, but verification did not pass')" -ForegroundColor Yellow
  } else {
    Write-Host "  ★ $(T '全部完成！' 'All done!')" -ForegroundColor Green
  }
  Write-Host "  $(T '厂商' 'Provider')   $($p.label) ($Model)"
  Write-Host "  model      $ModelId"
  Write-Host ""
  Write-Host "  $(T '现在怎么用：' 'How to start:')" -ForegroundColor Cyan
  Write-Host "    1. $(T '进入你的项目文件夹：' 'Go into your project folder:') cd <your-folder>"
  Write-Host "    2. $(T '输入命令启动：' 'Launch:') claude" -ForegroundColor Green
  Note (T "如果提示找不到 claude，关掉 PowerShell 重开一个再试" "If 'claude' is not found, reopen PowerShell")
  Note (T "想换别的模型：重跑本命令，选另一个就行" "To switch models: re-run and pick another")
  Write-Host "------------------------------------------------------------" -ForegroundColor DarkGray
}

# ---- main ------------------------------------------------------------------
if ($Help) { Show-Help; return }
if ($List) { Show-List; return }
if ($ModelSet -and -not $Providers.Contains($Model)) {
  Show-List
  Die (T "不支持的厂商 '$Model'" "Unsupported provider '$Model'")
}

Banner
Write-Host ""
Note (T "我会帮你：① 装好 Git + Claude Code  ② 接上你选的国产模型。约 3-5 分钟。" "I will: (1) install Git + Claude Code, (2) wire it to your China LLM. ~3-5 min.")

if (-not $ModelSet) { Select-Provider }
if (-not $KeySet)   { Acquire-Key }
Assert-ApiKeyLooksPlausible

Step-Prereq
Step-InstallClaude
Step-Configure
Step-Verify
Write-Progress -Activity "yiclaude" -Completed
Summary
